theme: jekyll-theme-dinky
title: R Adelaide
description: <img src="https://uofabioinformaticshub.github.io/RAdelaide-July-2018/images/UoA_logo_col_vert.png" alt="UofAlogo" border="0px" style="width:143px;height:106px;"><br><br>Course Homepage<br>July 2018
